### ISSUE TITLE
changes to language strings are lost after flushing main elgg cache

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/translation_editor#13] opened 2015-12-05 21:55 UTC
i have noticed occasionally for a long while that if i edit a language string in this plugin that sometimes the change is lost (not saved) or sometimes the change is saved, but does not get reflected in the live website and is totally lost after i flush the site's cache.
there are no errors in the php logs, so i don't have much to go on to understand this.
any ideas?

**Comment by propertunist** [comment] 2015-12-05 22:05
oh, after experimenting, i found that the problem here is actually that strings that end in a standard space character are stripped of their final character (the space character). if i type &nbsp; instead, then the space is rendered in the browser correctly.

**Comment by jdalsem** [comment] 2015-12-08 11:06
Then this is a duplicate of https://github.com/ColdTrick/translation_editor/issues/8

**Closed by jdalsem** 2015-12-08 11:06 UTC

**Comment by propertunist** [comment] 2015-12-08 11:22
ah ok, yes
