### ISSUE TITLE
The translation editor does not work consistantly...

### ISSUE THREAD

**Issue by siteleas** [ColdTrick/translation_editor#7] opened 2015-02-02 10:45 UTC
Hi there. Thanks for your efforts on the translation editor. I really want to be able to use it, but it seldom works. It worked for a couple of translated fields but then stopped functioning. I don't know how to diagnose the problem. Nothing shows up in an error_log file. Also, the problem occurs whether or not the translation editor is the only plugin installed and activated. So there is no conflict with other plugins. I literally completely removed all mods but the default mods and still when I click in a field, enter text and go to a new field, no message appears confirming save and no commit is made to the database table. I am using elgg 1.10.1.

Please help as I have translators ready to work but they have repeatedly tried the tool and are getting frustrated. I don't want to lose my team due to problems with the editor. I see you have done very good work and want to be able to take advantage of it. Thanks in advance for getting back to me quickly.

**Comment by jeabakker** [comment] 2015-02-02 11:42
i'm currently working on the 1.10 version. The 1.9 version should also work though. In all my testing it hasn't failed yet.

The translated strings aren't saved in the database but in dataroot. The easiest way to see if the plugin works is translate a simple string (like "activity" to for example "activityyyyyyyy") and if all goes well the menu item for activity should change (or the title of the activity page).
You can verify that the data was saved by going back to the plugin overview of translation editor, there should be a download and delete icon next to "core".

**Comment by jeabakker** [comment] 2015-02-02 11:43
I'll test with caching enabled soon (since my development site has this disabled

**Comment by siteleas** [comment] 2015-02-02 11:46
I have caching enabled. Perhaps this is the issue. The editor works for a couple of edits and then completely stops working (no more fields are saved).

**Comment by siteleas** [comment] 2015-02-02 11:48
I just tested the editor with the caching off and the editor works. So obviously there is a problem when it relates to using the editor with caching enabled.

**Comment by jeabakker** [comment] 2015-02-02 11:49
thanks for the info

**Comment by siteleas** [comment] 2015-02-02 11:50
That's an unfortunate thing since it would be great to have the ability to have teams edit the language files on a live site with caching enabled. Thanks for all of your work.

**Comment by jeabakker** [comment] 2015-02-02 12:20
could you please try the latest version from github. I made some changes to the plugin, this shouldn't have fixed/changed anything.

But i'm still unable to reproduce your problem. I have caching enabled and can still translate everything, even after 40+ edits it still works

Maybe it has something to do with the response times of the server. Does it matter if you translate fast (so type -> tab -> type -> tab) or slow ( so type ......... -> tab -> type ........ -> tab)?

**Comment by jdalsem** [comment] 2015-04-24 13:01
Closing this as we are unable to reproduce the issue

**Closed by jdalsem** 2015-04-24 13:01 UTC
